server:
  port: 0

spring:
  profiles: localdocker
  application:
    name: notification-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://127.0.0.1:8888
  kafka:
    bootstrap-servers: localhost:29092, localhost:29093, localhost:29094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      uri: mongodb://root:1234@127.0.0.1:27017/notifications

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.chunsun.notificationservice: DEBUG

