global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['i12a505.p.ssafy.io']
    metrics_path: '/api/auth-service/actuator/prometheus'
    scheme: http

  - job_name: 'member-service'
    static_configs:
      - targets: ['i12a505.p.ssafy.io']
    metrics_path: '/api/member-service/actuator/prometheus'
    scheme: http

  - job_name: 'coupon-service'
    static_configs:
      - targets: ['i12a505.p.ssafy.io']
    metrics_path: '/api/coupon-service/actuator/prometheus'
    scheme: http

  - job_name: 'rank-service'
    static_configs:
      - targets: ['i12a505.p.ssafy.io']
    metrics_path: '/api/rank-service/actuator/prometheus'
    scheme: http

  - job_name: 'payment-service'
    static_configs:
      - targets: ['i12a505.p.ssafy.io']
    metrics_path: '/api/payment-service/actuator/prometheus'
    scheme: http

  - job_name: 'class-service'
    static_configs:
      - targets: ['i12a505.p.ssafy.io']
    metrics_path: '/api/class-service/actuator/prometheus'
    scheme: http

  - job_name: 'chat-service'
    static_configs:
      - targets: ['i12a505.p.ssafy.io']
    metrics_path: '/api/chat-service/actuator/prometheus'
    scheme: http

  - job_name: 'notification-service'
    static_configs:
      - targets: ['i12a505.p.ssafy.io']
    metrics_path: '/api/notification-service/actuator/prometheus'
    scheme: http
