global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/{service}/actuator/prometheus'  # 이 부분 수정
    params:
      service: [auth-service, member-service, coupon-service, rank-service, payment-service, class-service, chat-service, notification-service]
    static_configs:
      - targets:
          - 'gateway-service:8080'  # 경로 제거하고 서비스만 남김
