global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/auth-service/actuator/prometheus'

  - job_name: 'member-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/member-service/actuator/prometheus'

  - job_name: 'coupon-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/coupon-service/actuator/prometheus'

  - job_name: 'rank-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/rank-service/actuator/prometheus'

  - job_name: 'payment-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/payment-service/actuator/prometheus'

  - job_name: 'class-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/class-service/actuator/prometheus'

  - job_name: 'chat-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/chat-service/actuator/prometheus'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['gateway-service:8080']
    metrics_path: '/notification-service/actuator/prometheus'
